# This is a basic workflow to help you get started with Actions

name: Windows CI Build

# Controls when the workflow will run
on:
  schedule:
  - cron: '0 3 * * *'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, windows, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Cleanup workspace to discard any artifact from previous runs
      - name: Cleanup workspace
        shell: powershell
        run: |
          Remove-Item -Recurse -Force .\artifacts -ErrorAction Ignore
     
      # Runs a single command using the runners shell
      - name: Run Build
        shell: powershell
        run : |
          md .\artifacts
          cd .\artifacts
          D:\repos\moulmahdi\sources\fdb_nightlies.ps1 -RunId ${{github.run_id}}
        
      # Publish build logs
      - uses: actions/upload-artifact@v2
        name: Publish Artifacts
        with:
          name: build_logs
          path: ${{ github.workspace }}/artifacts/build_logs
